zookeeper:
  image: eventuateio/eventuate-zookeeper:0.3.0.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: eventuateio/eventuate-kafka:0.3.0.RELEASE
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysqlbinlogpipeline:
  image: eventuateio/eventuate-mysql:0.3.0.RELEASE
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

postgrespollingpipeline:
  image: eventuateio/eventuate-postgres:0.3.0.RELEASE
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate

postgreswalpipeline:
  image: eventuateio/eventuate-postgres:0.3.0.RELEASE
  ports:
    - 5433:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate
